### ISSUE TITLE
Convert Volley to Retrofit

### ISSUE THREAD

**Issue by DroidPulkit** [DroidPulkit/TorontoWasteWizard#10]
As described above

**Comment by vincent-paing** [comment]
Can you list out the endpoints so that it's easier for contributors?

**Comment by henriquehorbovyi** [comment]
I would like to get this one :smiley:

**Comment by vincent-paing** [comment]
> I would like to get this one 😃

I already submitted a PR for this 😄

**Comment by DroidPulkit** [comment]
Sorry, guys I should have listed the endpoints, let me see your PR though :)
