### ISSUE TITLE
The favorites page is open many times

### ISSUE THREAD

**Issue by emersonsiega** [DroidPulkit/TorontoWasteWizard#14]
When I've used your app to create the gif for README, I found a strange behavior...
If you have 4 items added to favorite and open the favorites page, it is opened 4 times. It's kind a loop where the page is opened one time for each item.

If you press the back button you can see the pages being removed from stack.

I hope this helps.

**Comment by DroidPulkit** [comment]
Hi Thanks for reporting the issue. Will work on it

**Comment by vincent-paing** [comment]
Can I help with this?
