### ISSUE TITLE
Add gif of application working on Android to README.md

### ISSUE THREAD

**Issue by DroidPulkit** [DroidPulkit/TorontoWasteWizard#6]
Download the app from [play store ](https://play.google.com/store/apps/details?id=pulkit.com.torontowastewizard)and make a video to search for an object like apple, coffee or something from autocomplete and show the search result page, then adding the object to favourite and then showing the favourite page. We can convert video to gif from [this site](https://ezgif.com/video-to-gif)

**Comment by emersonsiega** [comment]
I'll do this tonight, if there's no problem :)

**Comment by DroidPulkit** [comment]
Sure, I am assigning it to you
